### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by liubenyuan** [BlackEdder/realtimeplot#1]
Hi, I found this project really interesting. I would like to draw some scientific plots for a realtime DAQ, is this project still active?

**Comment by BlackEdder** [comment]
I am not developing this project any more, but will take pull requests. I know libcca has been renamed to the [CAF framework](https://actor-framework.org/). I don't know how difficult it would be to port to that.

**Comment by liubenyuan** [comment]
Thanks, I am googling some C++ plot functions that can be used to plot or show images in real-time. Is this project related to the CAF framework? I do not finding anything in CAF related to real-time plotting.

**Comment by BlackEdder** [comment]
It depends on the CAF framework (formerly libcca) to communicate between different threads.

**Comment by liubenyuan** [comment]
Thank you.
